import React, { useState, useEffect } from 'react';
import { Row, Col, Card, Form, Button, Spinner, Table, Badge, Alert } from 'react-bootstrap';
import { useLocation, useNavigate } from 'react-router-dom';
import { supabase } from '../../config/supabase';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';

// Simplify API base
const SIMPLIFY_API_URL = 'https://workflow.simplifygenai.id/api/v1/prediction/c86edd85-f451-4bd6-8d7f-05a73c324c23';

// hit ke Contract Revision Agent - TRIAL
//const SIMPLIFY_API_URL = 'https://workflow.simplifygenai.id/api/v1/prediction/58c7ad94-1361-4556-a370-bdb965b25b15';



const ContractReviewUpdate = () => {
  const [contractData, setContractData] = useState(null);
  const [contractUpdates, setContractUpdates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [updating, setUpdating] = useState(false);
  const [revisedContract, setRevisedContract] = useState('');
  const [generatingContract, setGeneratingContract] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [wysiwygContent, setWysiwygContent] = useState('');
  const location = useLocation();
  const navigate = useNavigate();

  // Quill editor modules and formats
  const modules = {
    toolbar: [
      [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
      ['bold', 'italic', 'underline', 'strike'],
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      [{ 'indent': '-1'}, { 'indent': '+1' }],
      [{ 'color': [] }, { 'background': [] }],
      [{ 'align': [] }],
      ['link', 'image'],
      ['clean']
    ],
  };

  const formats = [
    'header', 'font', 'size',
    'bold', 'italic', 'underline', 'strike', 'blockquote',
    'list', 'bullet', 'indent',
    'link', 'image', 'color', 'background', 'align'
  ];

  // Handle direct access to the page without proper navigation state
  useEffect(() => {
    if (!location.state || !location.state.userEmail || !location.state.contractReviewId) {
      console.error('Direct access detected - missing navigation state');
      setError('This page requires proper navigation from the Contract Review page. Redirecting...');
      setLoading(false);
      setTimeout(() => {
        navigate('/contract-review');
      }, 2000);
    }
  }, [location.state, navigate]);

  useEffect(() => {
    const fetchContractData = async () => {
      try {
        setLoading(true);
        
        // Get data from location state (passed from contract-review)
        const { userEmail, contractReviewId } = location.state || {};
        console.log('ContractReviewUpdate: userEmail:', userEmail, 'contractReviewId:', contractReviewId);
        
        // Validate that both userEmail and contractReviewId are present and valid
        if (!userEmail || !contractReviewId) {
          console.error('Missing required parameters:', { userEmail, contractReviewId });
          setError('Missing required parameters: userEmail or contractReviewId');
          setLoading(false);
          // Auto-redirect to /contract-review after a short delay
          setTimeout(() => {
            navigate('/contract-review');
          }, 2000);
          return;
        }

        // Additional validation for contract_review_id format (should be 50 characters)
        if (contractReviewId.length !== 50) {
          console.error('Invalid contract_review_id format:', contractReviewId);
          setError('Invalid contract_review_id format');
          setLoading(false);
          // Auto-redirect to /contract-review after a short delay
          setTimeout(() => {
            navigate('/contract-review');
          }, 2000);
          return;
        }

        // Validate email format
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(userEmail)) {
          console.error('Invalid email format:', userEmail);
          setError('Invalid email format');
          setLoading(false);
          // Auto-redirect to /contract-review after a short delay
          setTimeout(() => {
            navigate('/contract-review');
          }, 2000);
          return;
        }

        console.log('Successfully received parameters:', { userEmail, contractReviewId });

        // Fetch contract data from master_contract table
        const { data: contractData, error: contractError } = await supabase
          .from('master_contract')
          .select('*')
          .eq('user_email', userEmail)
          .eq('contract_review_id', contractReviewId);
        console.log('Fetched contractData from DB:', contractData, 'Error:', contractError);

        if (contractError) {
          console.error('Error fetching contract data:', contractError);
          setError('Error fetching contract data: ' + contractError.message);
          setLoading(false);
          // Auto-redirect to /contract-review after a short delay
          setTimeout(() => {
            navigate('/contract-review');
          }, 2000);
          return;
        }

        // Check if contract data exists
        if (!contractData || contractData.length === 0) {
          console.error('No contract data found for:', { userEmail, contractReviewId });
          setError(`No contract data found for the provided parameters.\nuserEmail: ${userEmail}\ncontractReviewId: ${contractReviewId}`);
          setLoading(false);
          // Auto-redirect to /contract-review after a short delay
          setTimeout(() => {
            navigate('/contract-review');
          }, 4000);
          return;
        }

        setContractData(contractData[0] || null);
        // Always generate revised contract on page load
        setAutoGenerated(true);
        setTimeout(() => {
          generateRevisedContract(userEmail, contractReviewId);
        }, 500);
      } catch (error) {
        console.error('Error in fetchContractData:', error);
        setError('Error loading contract data: ' + error.message);
        setLoading(false);
        // Auto-redirect to /contract-review after a short delay
        setTimeout(() => {
          navigate('/contract-review');
        }, 2000);
      } finally {
        setLoading(false);
      }
    };

    fetchContractData();
  }, [location.state, navigate]);

  // Update WYSIWYG content when revised contract is generated
  useEffect(() => {
    if (revisedContract && autoGenerated) {
      setWysiwygContent(revisedContract);
    }
  }, [revisedContract, autoGenerated]);

  const handleUpdateStatus = async (updateId, newStatus) => {
    try {
      setUpdating(true);
      
      const { error } = await supabase
        .from('contract_updates')
        .update({ status: newStatus })
        .eq('id', updateId);

      if (error) {
        console.error('Error updating status:', error);
        alert('Error updating status: ' + error.message);
        return;
      }

      // Refresh the data
      const { data: updatedData, error: fetchError } = await supabase
        .from('contract_updates')
        .select('*')
        .eq('user_email', contractData?.user_email)
        .eq('contract_review_id', contractData?.contract_review_id);

      if (fetchError) {
        console.error('Error refreshing data:', fetchError);
      } else {
        setContractUpdates(updatedData || []);
      }

      alert('Status updated successfully!');
    } catch (error) {
      console.error('Error in handleUpdateStatus:', error);
      alert('Error updating status: ' + error.message);
    } finally {
      setUpdating(false);
    }
  };

  const getStatusBadge = (status) => {
    switch (status) {
      case 'completed':
        return <Badge bg="success">{status}</Badge>;
      case 'pending':
        return <Badge bg="warning" text="dark">{status}</Badge>;
      case 'in_progress':
        return <Badge bg="info">{status}</Badge>;
      case 'rejected':
        return <Badge bg="danger">{status}</Badge>;
      default:
        return <Badge bg="secondary">{status}</Badge>;
    }
  };

  const generateRevisedContract = async (userEmailOverride, contractReviewIdOverride) => {
    const userEmailToUse = userEmailOverride || contractData?.user_email;
    const contractReviewIdToUse = contractReviewIdOverride || contractData?.contract_review_id;
    if (!contractReviewIdToUse) {
      alert('Contract Review ID is required to generate revised contract.');
      return;
    }

    setGeneratingContract(true);
    try {
      console.log('Starting revised contract generation for ID:', contractReviewIdToUse);

      // 1. Fetch original contract text from master_contract table
      const { data: originalContract, error: originalError } = await supabase
        .from('master_contract')
        .select('original_pdf_text, contract_name')
        .eq('contract_review_id', contractReviewIdToUse)
        .eq('user_email', userEmailToUse)
        .eq('status', 'pending') // Get the original contract, not the generated one
        .single();

      if (originalError || !originalContract) {
        console.error('Error fetching original contract:', originalError);
        alert('Failed to fetch original contract data.');
        setGeneratingContract(false);
        return;
      }

      // 2. Fetch contract updates from contract_updates table
      const { data: updates, error: updatesError } = await supabase
        .from('contract_updates')
        .select('recommended_legal_amendment, original_clause, contractual_reference')
        .eq('contract_review_id', contractReviewIdToUse)
        .eq('user_email', userEmailToUse);

      if (updatesError) {
        console.error('Error fetching contract updates:', updatesError);
        alert('Failed to fetch contract updates.');
        setGeneratingContract(false);
        return;
      }

      if (!updates || updates.length === 0) {
        alert('No contract updates found. Please add some updates before generating revised contract.');
        setGeneratingContract(false);
        return;
      }

      console.log('Original contract text length:', originalContract.original_pdf_text?.length);
      console.log('Number of updates found:', updates.length);

      // 3. Format the update prompt
      const updatesText = updates.map((update, i) => {
        return `Update ${i + 1}:\n- Contractual Reference: ${update.contractual_reference || 'N/A'}\n- Original Clause: ${update.original_clause || 'N/A'}\n- Recommended Legal Amendment: ${update.recommended_legal_amendment || 'N/A'}\n`;
      }).join('\n');

      const prompt = `\nHere is the original employment contract:\n\n${originalContract.original_pdf_text}\n\nBelow are the contract updates to apply:\n\n${updatesText}\n\nPlease generate the full revised contract after applying these updates. Keep the structure, legal formatting, and numbering. Make sure to incorporate all the recommended legal amendments into the appropriate sections of the contract.\n`;

      console.log('Sending request to Simplify API...');

      // 4. Send to Simplify Agent
      const response = await fetch(SIMPLIFY_API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          question: prompt,
          chatId: contractReviewIdToUse,
          uploads: []
        })
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const result = await response.json();
      const output = result.text || result.output || '[No response from Simplify]';
      
      console.log('Simplify response received:', output.substring(0, 200) + '...');
      
      setRevisedContract(output);
      setWysiwygContent(output); // Set as default value in WYSIWYG

      // 5. Save the revised contract to database (always update on generation)
      const { error: saveError } = await supabase
        .from('master_contract')
        .update({ 
          revised_contract_text: output,
          updated_at: new Date().toISOString()
        })
        .eq('contract_review_id', contractReviewIdToUse)
        .eq('user_email', userEmailToUse)
        .eq('status', 'pending'); // Update the original contract record

      if (saveError) {
        console.error('Error saving revised contract:', saveError);
        alert('Revised contract generated successfully, but failed to save to database.');
      } else {
        console.log('Revised contract saved to database successfully');
      }

      // Automatically export to WORD after generation is complete
      await exportToWord();

    } catch (error) {
      console.error('Error generating revised contract:', error);
    } finally {
      setGeneratingContract(false);
    }
  };

  const exportToWord = async () => {
    if (!revisedContract) {
      alert('No revised contract available to export. Please generate a revised contract first.');
      return;
    }

    try {
      // Convert markdown to Word document structure
      const paragraphs = [];
      
      // Split the content by lines and process each line
      const lines = revisedContract.split('\n');
      
      for (const line of lines) {
        const trimmedLine = line.trim();
        
        if (!trimmedLine) {
          // Empty line - add spacing
          paragraphs.push(new Paragraph({}));
        } else if (trimmedLine.startsWith('# ')) {
          // Main heading
          paragraphs.push(
            new Paragraph({
              text: trimmedLine.substring(2),
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 400, after: 200 }
            })
          );
        } else if (trimmedLine.startsWith('## ')) {
          // Sub heading
          paragraphs.push(
            new Paragraph({
              text: trimmedLine.substring(3),
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 300, after: 150 }
            })
          );
        } else if (trimmedLine.startsWith('### ')) {
          // Sub sub heading
          paragraphs.push(
            new Paragraph({
              text: trimmedLine.substring(4),
              heading: HeadingLevel.HEADING_3,
              spacing: { before: 200, after: 100 }
            })
          );
        } else if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
          // Bullet point
          paragraphs.push(
            new Paragraph({
              text: trimmedLine.substring(2),
              bullet: { level: 0 },
              spacing: { before: 100, after: 100 }
            })
          );
        } else if (trimmedLine.startsWith('  - ') || trimmedLine.startsWith('  * ')) {
          // Nested bullet point
          paragraphs.push(
            new Paragraph({
              text: trimmedLine.substring(4),
              bullet: { level: 1 },
              spacing: { before: 100, after: 100 }
            })
          );
        } else if (trimmedLine.startsWith('**') && trimmedLine.endsWith('**')) {
          // Bold text
          paragraphs.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: trimmedLine.substring(2, trimmedLine.length - 2),
                  bold: true
                })
              ],
              spacing: { before: 100, after: 100 }
            })
          );
        } else {
          // Regular paragraph
          paragraphs.push(
            new Paragraph({
              text: trimmedLine,
              spacing: { before: 100, after: 100 }
            })
          );
        }
      }

      // Create the document
      const doc = new Document({
        sections: [
          {
            properties: {},
            children: [
              new Paragraph({
                text: `Revised Contract - ${contractData?.contract_name || 'Contract'}`,
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 400 }
              }),
              new Paragraph({
                text: `Generated on: ${new Date().toLocaleString()}`,
                spacing: { before: 200, after: 400 }
              }),
              ...paragraphs
            ]
          }
        ]
      });

      // Generate and download the document
      const blob = await Packer.toBlob(doc);
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `revised_contract_${contractData?.contract_review_id || 'contract'}.docx`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      alert('Contract exported to Word document successfully!');
      navigate('/contract-review');

    } catch (error) {
      console.error('Error exporting to Word:', error);
      alert('Error exporting to Word: ' + error.message);
    }
  };

  const saveEditedContract = async () => {
    try {
      const { error } = await supabase
        .from('master_contract')
        .update({ 
          revised_contract_text: wysiwygContent,
          updated_at: new Date().toISOString()
        })
        .eq('contract_review_id', contractData?.contract_review_id)
        .eq('status', 'pending');

      if (error) {
        console.error('Error saving edited contract:', error);
        alert('Error saving edited contract: ' + error.message);
      } else {
        alert('Edited contract saved successfully!');
      }
    } catch (error) {
      console.error('Error in saveEditedContract:', error);
      alert('Error saving edited contract: ' + error.message);
    }
  };

  if (loading) {
    return (
      <Row>
        <Col xl={12} xxl={12}>
          <Card>
            <Card.Body className="text-center">
              <Spinner animation="border" role="status">
                <span className="visually-hidden">Loading...</span>
              </Spinner>
              <p className="mt-2">Loading contract review data...</p>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    );
  }

  if (error) {
    return (
      <Row>
        <Col xl={12} xxl={12}>
          <Alert variant="danger">
            <Alert.Heading>❌ Error - Redirecting to Contract Review</Alert.Heading>
            <p>{error}</p>
            <hr />
            <p><strong>Received Parameters:</strong></p>
            <ul>
              <li><strong>User Email:</strong> {location.state?.userEmail || 'NOT PROVIDED'}</li>
              <li><strong>Contract Review ID:</strong> {location.state?.contractReviewId || 'NOT PROVIDED'}</li>
            </ul>
            <p><strong>Validation Results:</strong></p>
            <ul>
              <li>User Email Valid: {location.state?.userEmail ? '✅' : '❌'}</li>
              <li>Contract Review ID Valid: {location.state?.contractReviewId ? '✅' : '❌'}</li>
              <li>Email Format Valid: {location.state?.userEmail && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(location.state.userEmail) ? '✅' : '❌'}</li>
              <li>Contract Review ID Length Valid: {location.state?.contractReviewId && location.state.contractReviewId.length === 50 ? '✅' : '❌'}</li>
            </ul>
            <p className="mb-0">
              <small className="text-muted">
                You will be automatically redirected to the Contract Review page in 2 seconds...
              </small>
            </p>
          </Alert>
        </Col>
      </Row>
    );
  }

  // If auto-generated mode is active, show only the revised contract with WYSIWYG
  // HIDDEN: Contract Editor and Revised Contract Generated Successfully card
  /*
  if (autoGenerated) {
    return (
      <React.Fragment>
        <Row>
          <Col xl={12} xxl={12}>
            <Card>
              <Card.Header>
                <Card.Title as="h5">Revised Contract Editor</Card.Title>
              </Card.Header>
              <Card.Body>
                {generatingContract ? (
                  <div className="text-center">
                    <Spinner animation="border" role="status">
                      <span className="visually-hidden">Generating...</span>
                    </Spinner>
                    <p className="mt-2">Automatically generating revised contract...</p>
                  </div>
                ) : (
                  <div>
                    <Alert variant="success">
                      <Alert.Heading>✅ Revised Contract Generated Successfully</Alert.Heading>
                      <p>The revised contract has been automatically generated and loaded into the editor below. You can now edit and format the contract as needed.</p>
                    </Alert>
                    
                    <div className="mb-3">
                      <h6>Contract Editor:</h6>
                      <div style={{ height: '80vh', border: '1px solid #ccc', borderRadius: '4px' }}>
                        <ReactQuill
                          theme="snow"
                          value={wysiwygContent}
                          onChange={setWysiwygContent}
                          modules={modules}
                          formats={formats}
                          style={{ height: 'calc(80vh - 42px)' }}
                        />
                      </div>
                    </div>
                    
                    <div className="mt-3">
                      <Button 
                        variant="primary" 
                        size="sm"
                        onClick={saveEditedContract}
                        style={{ marginRight: '10px' }}
                      >
                        Save Edited Contract
                      </Button>
                      <Button 
                        variant="outline-primary" 
                        size="sm"
                        onClick={() => {
                          const blob = new Blob([wysiwygContent], { type: 'text/plain' });
                          const url = window.URL.createObjectURL(blob);
                          const link = document.createElement('a');
                          link.href = url;
                          link.download = `revised_contract_${contractData?.contract_review_id}.txt`;
                          document.body.appendChild(link);
                          link.click();
                          document.body.removeChild(link);
                          window.URL.revokeObjectURL(url);
                        }}
                        style={{ marginRight: '10px' }}
                      >
                        Download as Text
                      </Button>
                      <Button 
                        variant="outline-success" 
                        size="sm"
                        onClick={exportToWord}
                      >
                        Export to WORD
                      </Button>
                    </div>
                  </div>
                )}
              </Card.Body>
            </Card>
          </Col>
        </Row>
      </React.Fragment>
    );
  }
  */

  // Original view for manual mode (when not auto-generated)
  return (
    <React.Fragment>
      {/* HIDE: Contract Review Update card */}
      {/*
      <Row>
        <Col xl={12} xxl={12}>
          <Card>
            <Card.Header>
              <Card.Title as="h5">Contract Review Update</Card.Title>
            </Card.Header>
            <Card.Body>
              {contractData && (
                <div className="mb-4">
                  <h6>Contract Information</h6>
                  <p><strong>Contract Name:</strong> {contractData.contract_name}</p>
                  <p><strong>Review ID:</strong> {contractData.contract_review_id}</p>
                  <p><strong>User Email:</strong> {contractData.user_email}</p>
                  <p><strong>Status:</strong> {getStatusBadge(contractData.status)}</p>
                  <p><strong>Created:</strong> {new Date(contractData.created_at).toLocaleString()}</p>
                </div>
              )}
            </Card.Body>
          </Card>
        </Col>
      </Row>
      */}

      {/* HIDE: Successfully Posted Parameters card */}
      {/*
      <Row>
        <Col xl={12} xxl={12}>
          <Card>
            <Card.Header>
              <Card.Title as="h5">Successfully Posted Parameters</Card.Title>
            </Card.Header>
            <Card.Body>
              <Alert variant="success">
                <Alert.Heading>✅ Parameters Successfully Posted</Alert.Heading>
                <p>The following parameters were successfully received and validated:</p>
                <hr />
                <p><strong>User Email:</strong> {contractData?.user_email || 'N/A'}</p>
                <p><strong>Contract Review ID:</strong> {contractData?.contract_review_id || 'N/A'}</p>
                <p className="mb-0">
                  <small className="text-muted">
                    These parameters were successfully posted from the contract review page and validated.
                  </small>
                </p>
              </Alert>
            </Card.Body>
          </Card>
        </Col>
      </Row>
      */}

      <Row>
        <Col xl={12} xxl={12}>
          <Card>
            <Card.Header>
              <Card.Title as="h5">Generate Revised Contract</Card.Title>
            </Card.Header>
            <Card.Body>
              <Button 
                variant="primary" 
                size="lg"
                onClick={() => generateRevisedContract(contractData?.user_email, contractData?.contract_review_id)}
                disabled={generatingContract || contractUpdates.length === 0}
                style={{ marginBottom: '20px' }}
              >
                {generatingContract ? (
                  <>
                    <Spinner
                      as="span"
                      animation="border"
                      size="sm"
                      role="status"
                      aria-hidden="true"
                      className="me-2"
                    />
                    Generating Revised Contract...
                  </>
                ) : (
                  'Generate Revised Contract'
                )}
              </Button>
              
              {/* HIDE: No Contract Updates Available card */}
              {/*
              {contractUpdates.length === 0 && (
                <Alert variant="warning">
                  <Alert.Heading>No Contract Updates Available</Alert.Heading>
                  <p>
                    You need to have contract updates before generating a revised contract. 
                    Please ensure you have completed the contract review process with recommended amendments.
                  </p>
                </Alert>
              )}
              */}

              {/* HIDE: Generated Revised Contract textarea/card */}
              {/*
              {revisedContract && (
                <div className="mt-4">
                  <h6>Generated Revised Contract:</h6>
                  <div 
                    className="border p-3 bg-light" 
                    style={{ 
                      maxHeight: '400px', 
                      overflowY: 'auto',
                      whiteSpace: 'pre-wrap',
                      fontSize: '14px',
                      lineHeight: '1.5'
                    }}
                  >
                    {revisedContract}
                  </div>
                  <div className="mt-3">
                    <Button 
                      variant="outline-primary" 
                      size="sm"
                      onClick={() => {
                        const blob = new Blob([revisedContract], { type: 'text/plain' });
                        const url = window.URL.createObjectURL(blob);
                        const link = document.createElement('a');
                        link.href = url;
                        link.download = `revised_contract_${contractData?.contract_review_id}.txt`;
                        document.body.appendChild(link);
                        link.click();
                        document.body.removeChild(link);
                        window.URL.revokeObjectURL(url);
                      }}
                      style={{ marginRight: '10px' }}
                    >
                      Download Revised Contract
                    </Button>
                    <Button 
                      variant="outline-success" 
                      size="sm"
                      onClick={exportToWord}
                    >
                      Export to WORD
                    </Button>
                  </div>
                </div>
              )}
              */}

            </Card.Body>
          </Card>
        </Col>
      </Row>

      {/* HIDE: Back to Contract Review button */}
      {/*
      <Row>
        <Col xl={12} xxl={12} className="text-start">
          <Button 
            variant="secondary" 
            onClick={() => navigate('/contract-review')}
            style={{ marginTop: '20px' }}
          >
            Back to Contract Review
          </Button>
        </Col>
      </Row>
      */}
    </React.Fragment>
  );
};

export default ContractReviewUpdate; 